---
apiVersion: v1
kind: Namespace
metadata:
  name: graylog
  labels:
    istio-injection: disabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: graylog
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - image:  docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        name: elasticsearch
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: http.host
          value: 0.0.0.0
        - name: network.host
          value: 0.0.0.0
        - name: transport.host
          value: localhost
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 512Mi
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: graylog
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://graylog.rfed.io/
        - name: GRAYLOG_PASSWORD_SECRET
          value: g0ABP9MJnWCjWtBX9JHFgjKAmD3wGXP3E0JQNOKlquDHnCn5689QAF8rRL66HacXLPA6fvwMY8BZoVVw0JqHnSAZorDDOdCk
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: ff1fabb33af42c3c19f20a00bbf206edd28ba1da95ca666e8101e7517c85057c
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://mongo:27017/graylog
        - name: GRAYLOG_SERVER_JAVA_OPTS
          value: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB
            -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled
            -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          value: 0.0.0.0:9000
        image: graylog/graylog:4.1
        name: graylog
        resources: {}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 12201
          name: gelf-udp
          protocol: UDP
        - containerPort: 12201
          name: gelf-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog-tcp
          protocol: TCP
        - containerPort: 514
          name: syslog-udp
          protocol: UDP
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog
  namespace: graylog
spec:
  type: NodePort
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "514"
    port: 514
    targetPort: 514
  - name: 514-udp
    port: 514
    protocol: UDP
    targetPort: 514
  - name: 12201-udp
    port: 12201
    protocol: UDP
    targetPort: 12201
  - name: "5555"
    port: 5555
    targetPort: 5555
  selector:
    app: graylog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: graylog
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
        ports:
        - containerPort: 27017
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-persistent-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-claim
  namespace: graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: graylog
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: graylog-ingressroute
  namespace: graylog
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`graylog.rfed.io`)
      kind: Rule
      services:
        - name: graylog
          port: 9000