---
apiVersion: v1
kind: Namespace
metadata:
  name: flask
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask
  namespace: flask
  labels:
    app: flask
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: clemenko/dc18:0.2
        ports:
        - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: flask
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: flask
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: flask
    kubernetes.io/name: "flask"
  name: flask
  namespace: flask
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - name: redflaskis
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask
  namespace: flask
spec:
  rules:
  - host: ucp.dockr.life
    http:
      paths:
      - path: /flask/
        backend:
          serviceName: flask
          servicePort: 80
---
