apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak
        env:
        - name: KEYCLOAK_FRONTEND_URL
          value: "keycloak.rfed.io"
        - name: KEYCLOAK_HOSTNAME
          value: "keycloak.rfed.io"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "Pa22word"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_DISABLE-TRUST-MANAGER
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`keycloak.rfed.io`)
      services:
        - name: keycloak
          port: 8443
  tls:
    passthrough: true
