apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_URL
          value: "keycloak.rfed.xx"        
        - name: KEYCLOAK_HOST
          value: "keycloak.rfed.xx"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "Pa22word"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_DISABLE-TRUST-MANAGER
          value: "true"
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/data # not used
          subPath:
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "keycloak"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: keycloak.rfed.xx
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - keycloak.rfed.xx
    secretName: tls-ingress
---
# Navlinks
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: keycloak
spec:
  target: _blank
  description: Keycloak
  label: Keycloak
  sideLabel: external
  toURL: https://keycloak.rfed.io/admin/master/console/#/rancher