apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - web
    - tcp
  routes:
    - match: Host(`keycloak.rfed.xx`)
      kind: Rule
      services:
        - name: keycloak
          port: 80
  tls:
    secretName: tls-ingress
    domains: 
    - main: keycloak.rfed.xx
