apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`keycloak.rfed.xx`)
      services:
        - name: keycloak
          port: 80
  tls:
    secretName: tls-ingress
    domains: 
    - main: keycloak.rfed.xx