apiVersion: v1
kind: LimitRange
metadata:
  name: custom-limit-range
spec:
  limits:
  -
    default:
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      memory: 256Mi
      cpu: "0.5"
    max:
      memory: 512Mi
      cpu: "1"
    min:
      memory: 256Mi
      cpu: "0.5"
    type: Container