apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        command: ["/bin/sh", "-ce", "/usr/bin/docker-entrypoint.sh minio server /data --address :9000 --console-address :9001"]
        env:
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: Pa22word
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: minio-volume
          mountPath: "/data"
      volumes:
      - name: minio-volume
        persistentVolumeClaim:
          claimName: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  sessionAffinity: ClientIP
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
stringData:
  CRYPTO_KEY_VALUE: "sEFA/gCHH68nVKits2EthgpctAYvDUR7mQA23CFd4gLeENP2Qb9o3A=="
  CRYPTO_KEY_PROVIDER: "secret"

---

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
spec:
  storageClassName: "longhorn-crypto-per-volume"
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 250Mi
---