apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: neuvector-internal
  namespace: neuvector
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: neuvector-internal
  namespace: neuvector
spec:
  isCA: true
  dnsNames:
  - neuvector.internal
  secretName: neuvector-internal
  usages:
  - digital signature
  - key encipherment
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: neuvector-internal
