apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-ir
  namespace: openfaas
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`openfaas.dockr.life`)
      kind: Rule
      services:
        - name: gateway-external
          port: 8080