---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rancher
  namespace: cattle-system
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`rancher.rfed.io`)
      services:
        - name: rancher
          port: 80
  tls:
    secretName: tls-rancher-ingress
    domains:
    - main: rancher.rfed.io