apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher
  namespace: cattle-system
spec:
  entryPoints:
    - web
    - tcp
  routes:
    - match: Host(`rancher.rfed.xx`)
      kind: Rule
      services:
        - name: rancher
          port: 80
  tls:
    secretName: tls-rancher-ingress
    domains: 
    - main: rancher.rfed.xx