---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher
  namespace: cattle-system
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`rancher.rfed.xx`)
      services:
        - name: rancher
          port: 443
  tls:
    secretName: tls-rancher-ingress
    domains: 
    - main: rancher.rfed.xx