---
apiVersion: v1
kind: Namespace
metadata:
  name: splunk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
  namespace: splunk
  labels:
    apps: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - name: splunk
          image: splunk/splunk
          ports:
            - containerPort: 8000
            - containerPort: 8088
          env:
          - name: SPLUNK_START_ARGS
            value: "--accept-license"
          - name: SPLUNK_PASSWORD
            value: "Pa22word"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: splunk
  name: splunk
  namespace: splunk
spec:
  selector:
    app: splunk
  type: LoadBalancer
  ports:
  - name: splunk
    nodePort: 30300
    protocol: TCP
    port: 8000
  - name: splunkevent
    protocol: TCP
    port: 8088
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: splunk-ingressroute
  namespace: splunk
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`splunk.rfed.io`)
      kind: Rule
      services:
        - name: splunk
          port: 8000
