apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      app.kubernetes.io/name: stackrox
    name: allow-monitoring
    namespace: stackrox
  spec:
    ingress:
    - ports:
      - port: 9090
        protocol: TCP
    podSelector:
      matchExpressions:
      - {key: app, operator: In, values: [central, sensor, collector]}
    policyTypes:
    - Ingress